// @flow
export const EXCHANGE_FIELD_UPDATE = 'EXCHANGE_FIELD_UPDATE';
export const EXCHANGE_ACTIVE_UPDATE = 'EXCHANGE_ACTIVE_UPDATE';
export const EXCHANGE_TRANSACTION_MAKE = 'EXCHANGE_TRANSACTION_MAKE';
